version: '3.1'

services:
  s_pdb:
      container_name: c_pdb
      image: postgres
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=123456
        - PGDATA=/var/lib/postgresql/data/pgdata
        - POSTGRES_USER=burakhayirli
        - POSTGRES_DB=test_db
      volumes:
        - ./data/ :/var/lib/postgresql/data/pgdata